/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    network.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "6770925d2803cfc24528c45bb3ba8b791b2a83e4"
 * GIT_BRANCH      "STAI-4.0"
 * GIT_DESCRIPTION "atonn-v1.1.3-275-g6770925d"
 *
 * Command Line options:
 * --load-mdesc-file = "/opt/ST/STEdgeAI/4.0/Utilities/configs/stm32n6"
 * --load-cdesc-file = "/opt/ST/STEdgeAI/4.0/Utilities/configs/cortex-m55"
 * --load-mpool-file = "/home/maria/.stm32cubeaistudio/workspace/stm32-model-example-int8/.ai/memory_pool"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "/home/maria/.stm32cubeaistudio/workspace/stm32-model-example-int8/.ai/st_ai_output/model_int8_OE_3_3_1_Q.json"
 * --Os = true
 * --Ocache-opt = true
 * --enable-epoch-controller = true
 * --output-info-file = "c_info"
 * --onnx-input = "/home/maria/.stm32cubeaistudio/workspace/stm32-model-example-int8/.ai/st_ai_output/model_int8_OE_3_3_1.onnx"
 * --out-dir-prefix = "/home/maria/.stm32cubeaistudio/workspace/stm32-model-example-int8/.ai/st_ai_ws/neural_art__network/"
 * --network-name = "network"
 * --generate-stai = true
 * --Oauto-sched = true
 *
 * auto* option expanded into:
 *   alt-scheduler = false
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"
#include "ecloader.h"
#include "ll_aton_cipher.h"

#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 3 || LL_ATON_VERSION_DEV != 275
#  error "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* global pool 8 is 99.31 KB */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x71000000  relative_mode size=117440512 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
extern unsigned char _mem_pool_xSPI2_network[]; /* [101697]; */
/* global pool 7 is ? */
/* index=7 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=33554424 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 1 is 16.00 KB */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x342e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x34270000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM3 name=npuRAM3 offset=0x34200000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x34350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 11 is 1.89 MB */
/* index=11 file postfix=AXISRAM2_AXISRAM3_AXISRAM4_AXISRAM5_AXISRAM6 name=cpuRAM2_npuRAM3_npuRAM4_npuRAM5_npuRAM6 offset=0x34100000  absolute_mode size=2883576 vpool READ_WRITE THROUGHPUT=HIGH LATENCY=MID byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=91  */
/* global pool 4 is 1.00 MB */
/* index=4 file postfix=AXISRAM2 name=cpuRAM2 offset=0x34100000  absolute_mode size=1048576 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXISRAM1 name=cpuRAM1 offset=0x34064000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 6 is ? */
/* index=6 file postfix=AXIFLEXMEM name=flexMEM offset=0x34000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */


const LL_Streng_EncryptionTypedef *LL_ATON_WeightEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

const LL_Streng_EncryptionTypedef *LL_ATON_BlobEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

#include "network_ecblobs.h"

/* scheduling epoch=0    nodes=52  ------------------------------------------------------------------- */

// Epoch Controller Blob (name='_ec_blob_network_1') micro instructions needed

// Epoch Controller Blob (name='_ec_blob_network_1') start function
static void _ec_blob_cache_start_func_1(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance) {
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 16384))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */, 16384);

};


/* scheduling DONE                 ------------------------------------------------------------------- */

const LL_ATON_RT_EpochBlockItem_t *LL_ATON_EpochBlockItems_network(void) {

  static const LL_ATON_RT_EpochBlockItem_t ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = _ec_blob_cache_start_func_1,
      .end_epoch_block = NULL,
      .blob_address = (uintptr_t)(_ec_blob_network_1_address),
      .wait_mask = 0,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_blob | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 15,
      .estimated_npu_cycles = 6482603,
      .estimated_tot_cycles = 9726635,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_1_128_128[] = { 1, 128, 128, 1 };
  static const uint32_t buff_info__mem_shape_F_1_1_128_128[] = { 1, 1, 128, 128 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 0.00381391774863005 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { -128 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_32_1_3_3[] = { 32, 3, 3, 1 };
  static const uint32_t buff_info__mem_shape_F_32_1_3_3[] = { 32, 1, 3, 3 };
  static const float buff_info_Conv2D_4_weights_quant_scale[] = { 0.0021973648108542, 0.00239428994245827, 0.00300651579163969, 0.00265650660730898, 0.00226501957513392, 0.00435238098725677, 0.00220993696711957, 0.00284609827212989, 0.0033829954918474, 0.0020611600484699, 0.00249125715345144, 0.00253961840644479, 0.00329090771265328, 0.00230950489640236, 0.00253758695907891, 0.00395214837044477, 0.00250039622187614, 0.0021640055347234, 0.00398830277845263, 0.00420850608497858, 0.00160789501387626, 0.00220597465522587, 0.00278823729604483, 0.00324112409725785, 0.003136504907161, 0.00288274651393294, 0.00346180587075651, 0.00231332564726472, 0.00268918741494417, 0.00241468590684235, 0.00248017418198287, 0.0035160044208169 };
  static const int16_t buff_info_Conv2D_4_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_32_32_3_3[] = { 32, 3, 3, 32 };
  static const uint32_t buff_info__mem_shape_M8_32_32_3_3[] = { 32, 4, 3, 3, 8 };
  static const float buff_info_Conv2D_8_weights_quant_scale[] = { 0.00429365877062082, 0.00429462222382426, 0.00399175053462386, 0.00365320360288024, 0.00364810647442937, 0.000485209486214444, 0.00354392873123288, 0.00447339145466685, 0.00284865382127464, 0.00331079820170999, 0.00391313480213284, 0.000605238776188344, 0.004116615280509, 0.000542935042176396, 0.00427667982876301, 0.00276631955057383, 0.0028299274854362, 0.00454186229035258, 0.00305454479530454, 0.00324101792648435, 0.0036920621059835, 0.00346897472627461, 0.00361153483390808, 0.00264841341413558, 0.00293220323510468, 0.00252276053652167, 0.00380716403014958, 0.00302818836644292, 0.00389260915108025, 0.00083879561861977, 0.00407989043742418, 0.000545865157619119 };
  static const int16_t buff_info_Conv2D_8_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_12_weights_quant_scale[] = { 0.00106571370270103, 0.0015190594131127, 0.00294399331323802, 0.00123082869686186, 0.000855563441291451, 0.00162296183407307, 0.000807036005426198, 0.00191270175855607, 0.0010882398346439, 0.000705999380443245, 0.00121654581744224, 0.00302220461890101, 0.00176105299033225, 0.00137428019661456, 0.00139387371018529, 0.00126743235159665, 0.0014644522452727, 0.000651113456115127, 0.00238345633260906, 0.00190017546992749, 0.00136139173991978, 0.001915741013363, 0.000570626580156386, 0.00060024915728718, 0.000987336970865726, 0.000805503746960312, 0.00139706814661622, 0.00191398663446307, 0.000966378371231258, 0.000743123237043619, 0.00181270251050591, 0.000711767643224448 };
  static const int16_t buff_info_Conv2D_12_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_16_weights_quant_scale[] = { 0.00131122535094619, 0.000580171821638942, 0.00123871956020594, 0.000597435340750962, 0.000513010192662477, 0.00185896956827492, 0.00234576594084501, 0.00223843683488667, 0.000643155130092055, 0.000913174590095878, 0.000611925846897066, 0.00171706988476217, 0.00191013212315738, 0.00218269042670727, 0.00165809865575284, 0.000677221105434, 0.00218386109918356, 0.00204400788061321, 0.000872221193276346, 0.00169277493841946, 0.00160776078701019, 0.00204183370806277, 0.000538016785867512, 0.00195285386871547, 0.00222631194628775, 0.00169481721241027, 0.00145783578045666, 0.00221237260848284, 0.00118746515363455, 0.00161197292618454, 0.0028262073174119, 0.00209182291291654 };
  static const int16_t buff_info_Conv2D_16_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_20_weights_quant_scale[] = { 0.00148553226608783, 0.00368955871090293, 0.00212655332870781, 0.00252838572487235, 0.00216341600753367, 0.00314531452022493, 0.0025343403685838, 0.00181318807881325, 0.00212331931106746, 0.00286723184399307, 0.000633087358437479, 0.00122975488193333, 0.00280092004686594, 0.00589071307331324, 0.00175722735002637, 0.00117700884584337, 0.00388429313898087, 0.000639270059764385, 0.00102405541110784, 0.00305300019681454, 0.00231198943220079, 0.00261910585686564, 0.00212272722274065, 0.00159395218361169, 0.00266148685477674, 0.00232718116603792, 0.00280573847703636, 0.00238740257918835, 0.003611677326262, 0.00264246226288378, 0.00328624085523188, 0.00310385832563043 };
  static const int16_t buff_info_Conv2D_20_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_24_weights_quant_scale[] = { 0.00144786038435996, 0.0024195855949074, 0.00144941592589021, 0.00173052202444524, 0.00206153257749975, 0.000999248470179737, 0.00117934483569115, 0.00258356356061995, 0.00307703204452991, 0.00163105467800051, 0.000543792732059956, 0.00374460313469172, 0.00178665434941649, 0.00182753382250667, 0.00168480770662427, 0.00185099407099187, 0.00353244505822659, 0.00120945053640753, 0.00170486536808312, 0.00163119600620121, 0.0022314649540931, 0.00329904467798769, 0.00132417061831802, 0.00168515602126718, 0.00237488397397101, 0.00154479418415576, 0.00144463090691715, 0.00182462844531983, 0.00210188794881105, 0.00180717010516673, 0.00176252098754048, 0.00117900467012078 };
  static const int16_t buff_info_Conv2D_24_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_28_weights_quant_scale[] = { 0.00139899901114404, 0.00143268855754286, 0.00132108351681381, 0.000532849866431206, 0.000883692933712155, 0.00209788396023214, 0.00120972935110331, 0.00137588742654771, 0.00459292344748974, 0.00262858346104622, 0.000982137280516326, 0.00117943168152124, 0.00117660092655569, 0.00206002895720303, 0.00125553912948817, 0.00144454196561128, 0.00104613078292459, 0.00137069774791598, 0.00161435978952795, 0.00152093439828604, 0.000473189778858796, 0.00166851258836687, 0.00197291327640414, 0.00217091641388834, 0.00210568332113326, 0.00214846082963049, 0.00127942336257547, 0.00178538844920695, 0.000877427286468446, 0.00142086413688958, 0.00193504896014929, 0.0026435349136591 };
  static const int16_t buff_info_Conv2D_28_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_32_weights_quant_scale[] = { 0.00137763645034283, 0.000577518600039184, 0.00144796725362539, 0.0019408380612731, 0.0013134169857949, 0.00329232262447476, 0.00120531325228512, 0.000600360159296542, 0.00145120092201978, 0.00242696073837578, 0.00102197215892375, 0.000522015558090061, 0.00095439376309514, 0.00275603029876947, 0.00124621705617756, 0.000957485055550933, 0.00228931242600083, 0.00109433534089476, 0.00197916571050882, 0.00233631441369653, 0.00218713097274303, 0.00175729999318719, 0.00132130365818739, 0.00121145183220506, 0.00266071478836238, 0.00124368746764958, 0.0015148970996961, 0.000502254697494209, 0.00118054659105837, 0.00265598832629621, 0.00158154335804284, 0.00201585539616644 };
  static const int16_t buff_info_Conv2D_32_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_36_weights_quant_scale[] = { 0.00124148593749851, 0.00140064070001245, 0.00122740468941629, 0.00255723879672587, 0.00109325221274048, 0.00135568412952125, 0.000878363789524883, 0.000869505864102393, 0.00143010553438216, 0.00112950755283237, 0.0014773701550439, 0.00108799058943987, 0.000532559992279857, 0.00154589605517685, 0.00105232791975141, 0.00116385030560195, 0.000619681843090802, 0.000678583281114697, 0.00159727258142084, 0.00122558092698455, 0.000843681918922812, 0.00133301725145429, 0.00154294236563146, 0.00225981953553855, 0.000764635624364018, 0.000691267661750317, 0.00151638372335583, 0.00112445221748203, 0.000933786213863641, 0.00109392742160708, 0.00114271545317024, 0.00206592679023743 };
  static const int16_t buff_info_Conv2D_36_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_40_weights_quant_scale[] = { 0.000612998090218753, 0.0022343487944454, 0.00127158546820283, 0.00813279300928116, 0.00160048168618232, 0.00142657128162682, 0.00108452746644616, 0.00205863919109106, 0.00182167859748006, 0.00111464178189635, 0.000906924076844007, 0.00184899137821048, 0.00132902408950031, 0.000953952549025416, 0.00241775228641927, 0.00110344041604549, 0.000842060369905084, 0.00174340046942234, 0.00369062297977507, 0.00273601990193129, 0.000855491263791919, 0.00108939490746707, 0.00195145234465599, 0.00388062931597233, 0.00113554135896266, 0.00186345668043941, 0.00130714650731534, 0.00119790690951049, 0.00225183391012251, 0.00115370645653456, 0.00134460511617362, 0.00136597524397075 };
  static const int16_t buff_info_Conv2D_40_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_44_weights_quant_scale[] = { 0.00209895288571715, 0.00137904367875308, 0.00145720725413412, 0.0017332237912342, 0.00412221858277917, 0.00342283537611365, 0.00138194102328271, 0.00220177113078535, 0.00175036035943776, 0.00238281348720193, 0.00191790971439332, 0.00126685353461653, 0.00182280573062599, 0.00247658952139318, 0.00127510935999453, 0.00143059424590319, 0.00294445618055761, 0.00180447939783335, 0.00146365561522543, 0.00142576720099896, 0.00421419879421592, 0.00163740885909647, 0.00191675929818302, 0.00179143960122019, 0.00221731537021697, 0.00179276335984468, 0.00128022488206625, 0.00178202660754323, 0.00451074866577983, 0.00190902000758797, 0.00136518804356456, 0.00401701917871833 };
  static const int16_t buff_info_Conv2D_44_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_48_weights_quant_scale[] = { 0.00234469841234386, 0.00235625333152711, 0.00223264680244029, 0.00225609936751425, 0.00192857382353395, 0.00164254859555513, 0.00222142459824681, 0.00274791102856398, 0.00214581424370408, 0.00168968155048788, 0.00226286496035755, 0.00175136490724981, 0.00225726142525673, 0.00136740237940103, 0.00244583515450358, 0.00194522785022855, 0.00293335551396012, 0.00179358688183129, 0.00223375530913472, 0.000861986365634948, 0.00168854219373316, 0.00238443724811077, 0.00246002618223429, 0.00215356168337166, 0.00191888783592731, 0.00180242676287889, 0.00221727113239467, 0.00261878431774676, 0.00262079364620149, 0.00215735728852451, 0.00224869675002992, 0.00163540872745216 };
  static const int16_t buff_info_Conv2D_48_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_1_32_1_1[] = { 1, 1, 1, 32 };
  static const uint32_t buff_info__mem_shape_F_1_32_1_1[] = { 1, 32, 1, 1 };
  static const float buff_info_Conv2D_51_weights_quant_scale[] = { 0.00303781242109835 };
  static const int16_t buff_info_Conv2D_51_weights_quant_offset[] = { 0 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 16384,
      .offset_limit = 16448,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_1_128_128,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1_128_128,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Conv2D_4_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 101376,
      .offset_end = 101664,
      .offset_limit = 101728,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_32_1_3_3,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_1_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_4_weights_quant_scale,
      .offset = buff_info_Conv2D_4_weights_quant_offset,
    },
    {
      .name = "Conv2D_8_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 0,
      .offset_end = 9216,
      .offset_limit = 9280,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_8_weights_quant_scale,
      .offset = buff_info_Conv2D_8_weights_quant_offset,
    },
    {
      .name = "Conv2D_12_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 9216,
      .offset_end = 18432,
      .offset_limit = 18496,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_12_weights_quant_scale,
      .offset = buff_info_Conv2D_12_weights_quant_offset,
    },
    {
      .name = "Conv2D_16_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 18432,
      .offset_end = 27648,
      .offset_limit = 27712,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_16_weights_quant_scale,
      .offset = buff_info_Conv2D_16_weights_quant_offset,
    },
    {
      .name = "Conv2D_20_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 27648,
      .offset_end = 36864,
      .offset_limit = 36928,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_20_weights_quant_scale,
      .offset = buff_info_Conv2D_20_weights_quant_offset,
    },
    {
      .name = "Conv2D_24_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 36864,
      .offset_end = 46080,
      .offset_limit = 46144,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_24_weights_quant_scale,
      .offset = buff_info_Conv2D_24_weights_quant_offset,
    },
    {
      .name = "Conv2D_28_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 46080,
      .offset_end = 55296,
      .offset_limit = 55360,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_28_weights_quant_scale,
      .offset = buff_info_Conv2D_28_weights_quant_offset,
    },
    {
      .name = "Conv2D_32_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 55296,
      .offset_end = 64512,
      .offset_limit = 64576,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_32_weights_quant_scale,
      .offset = buff_info_Conv2D_32_weights_quant_offset,
    },
    {
      .name = "Conv2D_36_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 64512,
      .offset_end = 73728,
      .offset_limit = 73792,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_36_weights_quant_scale,
      .offset = buff_info_Conv2D_36_weights_quant_offset,
    },
    {
      .name = "Conv2D_40_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 73728,
      .offset_end = 82944,
      .offset_limit = 83008,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_40_weights_quant_scale,
      .offset = buff_info_Conv2D_40_weights_quant_offset,
    },
    {
      .name = "Conv2D_44_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 82944,
      .offset_end = 92160,
      .offset_limit = 92224,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_44_weights_quant_scale,
      .offset = buff_info_Conv2D_44_weights_quant_offset,
    },
    {
      .name = "Conv2D_48_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 92160,
      .offset_end = 101376,
      .offset_limit = 101440,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_48_weights_quant_scale,
      .offset = buff_info_Conv2D_48_weights_quant_offset,
    },
    {
      .name = "Conv2D_51_weights",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 101664,
      .offset_end = 101697,
      .offset_limit = 101768,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 32,
      .mem_shape = buff_info__mem_shape_F_1_32_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_32_1_1,
      .per_channel = 0,
      .scale = buff_info_Conv2D_51_weights_quant_scale,
      .offset = buff_info_Conv2D_51_weights_quant_offset,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_1_128_128[] = { 1, 128, 128, 1 };
  static const uint32_t buff_info__mem_shape_F_1_1_128_128[] = { 1, 1, 128, 128 };
  static const float buff_info_Quantize_52_out_0_quant_scale[] = { 10.7385692596436 };
  static const int16_t buff_info_Quantize_52_out_0_quant_offset[] = { 73 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Quantize_52_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 16384,
      .offset_limit = 16448,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 14,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_1_128_128,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1_128_128,
      .per_channel = 0,
      .scale = buff_info_Quantize_52_out_0_quant_scale,
      .offset = buff_info_Quantize_52_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_network(void)
{
  return NULL;
}

