
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_network.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_NETWORK_H
#define __STAI_ATON_NETWORK_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_NETWORK_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_NETWORK_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_network_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_network_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_network_get_context_size(void)
{
  return STAI_NETWORK_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_network_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_network_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_network_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_network_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_NETWORK_STATES_NUM  (0)
#define STAI_NETWORK_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_NETWORK_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_NETWORK_IN_NUM (1)
#define STAI_NETWORK_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_NETWORK_IN_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_IN_SIZES \
  { \
    16384 \
  }
#define STAI_NETWORK_IN_SIZES_BYTES \
  { \
    16384 \
  }

#define STAI_NETWORK_IN_1_ALIGNMENT (32)
#define STAI_NETWORK_IN_1_NAME "Input_0_out_0"
#define STAI_NETWORK_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_FIRST)
#define STAI_NETWORK_IN_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_IN_1_SIZE (16384)
#define STAI_NETWORK_IN_1_SIZE_BYTES (16384)
#define STAI_NETWORK_IN_1_CHANNEL (1)
#define STAI_NETWORK_IN_1_HEIGHT (128)
#define STAI_NETWORK_IN_1_WIDTH (128)
#define STAI_NETWORK_IN_1_BATCH (1)
#define STAI_NETWORK_IN_1_RANK (4)
#define STAI_NETWORK_IN_1_SHAPE \
  { \
    1, 128, 128, 1 \
  }
#define STAI_NETWORK_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_IN_1_SCALES \
  { \
    0.00381391774863005 \
  }
#define STAI_NETWORK_IN_1_OFFSETS \
  { \
    -128 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_NETWORK_OUT_NUM (1)
#define STAI_NETWORK_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_OUT_NAMES \
  { \
    "Quantize_52_out_0" \
  }
#define STAI_NETWORK_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_OUT_SIZES \
  { \
    16384 \
  }
#define STAI_NETWORK_OUT_SIZES_BYTES \
  { \
    16384 \
  }

#define STAI_NETWORK_OUT_1_ALIGNMENT (32)
#define STAI_NETWORK_OUT_1_NAME "Quantize_52_out_0"
#define STAI_NETWORK_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_NETWORK_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_OUT_1_SIZE (16384)
#define STAI_NETWORK_OUT_1_SIZE_BYTES (16384)
#define STAI_NETWORK_OUT_1_CHANNEL (1)
#define STAI_NETWORK_OUT_1_HEIGHT (128)
#define STAI_NETWORK_OUT_1_WIDTH (128)
#define STAI_NETWORK_OUT_1_BATCH (1)
#define STAI_NETWORK_OUT_1_RANK (4)
#define STAI_NETWORK_OUT_1_SHAPE \
  { \
    1, 128, 128, 1 \
  }
#define STAI_NETWORK_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_OUT_1_SCALES \
  { \
    10.7385692596436 \
  }
#define STAI_NETWORK_OUT_1_OFFSETS \
  { \
    73 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_WEIGHTS_NUM (13)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
    32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32 \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
    "Conv2D_4_weights", "Conv2D_8_weights", "Conv2D_12_weights", "Conv2D_16_weights", "Conv2D_20_weights", "Conv2D_24_weights", "Conv2D_28_weights", "Conv2D_32_weights", "Conv2D_36_weights", "Conv2D_40_weights", "Conv2D_44_weights", "Conv2D_48_weights", "Conv2D_51_weights" \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
    288, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 32 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
    288, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 9216, 32 \
  }

#define STAI_NETWORK_WEIGHTS_1_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_1_NAME "Conv2D_4_weights"
#define STAI_NETWORK_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_1_SIZE (288)
#define STAI_NETWORK_WEIGHTS_1_SIZE_BYTES (288)
#define STAI_NETWORK_WEIGHTS_1_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_1_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_1_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_1_BATCH (1)
#define STAI_NETWORK_WEIGHTS_1_RANK (4)
#define STAI_NETWORK_WEIGHTS_1_SHAPE \
  { \
    32, 3, 3, 1 \
  }
#define STAI_NETWORK_WEIGHTS_1_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_1_SCALES \
  { \
    0.0021973648108542, 0.00239428994245827, 0.00300651579163969, 0.00265650660730898, 0.00226501957513392, 0.00435238098725677, 0.00220993696711957, 0.00284609827212989, 0.0033829954918474, 0.0020611600484699, 0.00249125715345144, 0.00253961840644479, 0.00329090771265328, 0.00230950489640236, 0.00253758695907891, 0.00395214837044477, 0.00250039622187614, 0.0021640055347234, 0.00398830277845263, 0.00420850608497858, 0.00160789501387626, 0.00220597465522587, 0.00278823729604483, 0.00324112409725785, 0.003136504907161, 0.00288274651393294, 0.00346180587075651, 0.00231332564726472, 0.00268918741494417, 0.00241468590684235, 0.00248017418198287, 0.0035160044208169 \
  }
#define STAI_NETWORK_WEIGHTS_1_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_2_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_2_NAME "Conv2D_8_weights"
#define STAI_NETWORK_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_2_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_2_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_2_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_2_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_2_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_2_BATCH (8)
#define STAI_NETWORK_WEIGHTS_2_RANK (5)
#define STAI_NETWORK_WEIGHTS_2_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_2_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_2_SCALES \
  { \
    0.00429365877062082, 0.00429462222382426, 0.00399175053462386, 0.00365320360288024, 0.00364810647442937, 0.000485209486214444, 0.00354392873123288, 0.00447339145466685, 0.00284865382127464, 0.00331079820170999, 0.00391313480213284, 0.000605238776188344, 0.004116615280509, 0.000542935042176396, 0.00427667982876301, 0.00276631955057383, 0.0028299274854362, 0.00454186229035258, 0.00305454479530454, 0.00324101792648435, 0.0036920621059835, 0.00346897472627461, 0.00361153483390808, 0.00264841341413558, 0.00293220323510468, 0.00252276053652167, 0.00380716403014958, 0.00302818836644292, 0.00389260915108025, 0.00083879561861977, 0.00407989043742418, 0.000545865157619119 \
  }
#define STAI_NETWORK_WEIGHTS_2_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_3_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_3_NAME "Conv2D_12_weights"
#define STAI_NETWORK_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_3_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_3_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_3_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_3_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_3_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_3_BATCH (8)
#define STAI_NETWORK_WEIGHTS_3_RANK (5)
#define STAI_NETWORK_WEIGHTS_3_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_3_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_3_SCALES \
  { \
    0.00106571370270103, 0.0015190594131127, 0.00294399331323802, 0.00123082869686186, 0.000855563441291451, 0.00162296183407307, 0.000807036005426198, 0.00191270175855607, 0.0010882398346439, 0.000705999380443245, 0.00121654581744224, 0.00302220461890101, 0.00176105299033225, 0.00137428019661456, 0.00139387371018529, 0.00126743235159665, 0.0014644522452727, 0.000651113456115127, 0.00238345633260906, 0.00190017546992749, 0.00136139173991978, 0.001915741013363, 0.000570626580156386, 0.00060024915728718, 0.000987336970865726, 0.000805503746960312, 0.00139706814661622, 0.00191398663446307, 0.000966378371231258, 0.000743123237043619, 0.00181270251050591, 0.000711767643224448 \
  }
#define STAI_NETWORK_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_4_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_4_NAME "Conv2D_16_weights"
#define STAI_NETWORK_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_4_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_4_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_4_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_4_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_4_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_4_BATCH (8)
#define STAI_NETWORK_WEIGHTS_4_RANK (5)
#define STAI_NETWORK_WEIGHTS_4_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_4_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_4_SCALES \
  { \
    0.00131122535094619, 0.000580171821638942, 0.00123871956020594, 0.000597435340750962, 0.000513010192662477, 0.00185896956827492, 0.00234576594084501, 0.00223843683488667, 0.000643155130092055, 0.000913174590095878, 0.000611925846897066, 0.00171706988476217, 0.00191013212315738, 0.00218269042670727, 0.00165809865575284, 0.000677221105434, 0.00218386109918356, 0.00204400788061321, 0.000872221193276346, 0.00169277493841946, 0.00160776078701019, 0.00204183370806277, 0.000538016785867512, 0.00195285386871547, 0.00222631194628775, 0.00169481721241027, 0.00145783578045666, 0.00221237260848284, 0.00118746515363455, 0.00161197292618454, 0.0028262073174119, 0.00209182291291654 \
  }
#define STAI_NETWORK_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_5_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_5_NAME "Conv2D_20_weights"
#define STAI_NETWORK_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_5_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_5_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_5_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_5_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_5_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_5_BATCH (8)
#define STAI_NETWORK_WEIGHTS_5_RANK (5)
#define STAI_NETWORK_WEIGHTS_5_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_5_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_5_SCALES \
  { \
    0.00148553226608783, 0.00368955871090293, 0.00212655332870781, 0.00252838572487235, 0.00216341600753367, 0.00314531452022493, 0.0025343403685838, 0.00181318807881325, 0.00212331931106746, 0.00286723184399307, 0.000633087358437479, 0.00122975488193333, 0.00280092004686594, 0.00589071307331324, 0.00175722735002637, 0.00117700884584337, 0.00388429313898087, 0.000639270059764385, 0.00102405541110784, 0.00305300019681454, 0.00231198943220079, 0.00261910585686564, 0.00212272722274065, 0.00159395218361169, 0.00266148685477674, 0.00232718116603792, 0.00280573847703636, 0.00238740257918835, 0.003611677326262, 0.00264246226288378, 0.00328624085523188, 0.00310385832563043 \
  }
#define STAI_NETWORK_WEIGHTS_5_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_6_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_6_NAME "Conv2D_24_weights"
#define STAI_NETWORK_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_6_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_6_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_6_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_6_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_6_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_6_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_6_BATCH (8)
#define STAI_NETWORK_WEIGHTS_6_RANK (5)
#define STAI_NETWORK_WEIGHTS_6_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_6_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_6_SCALES \
  { \
    0.00144786038435996, 0.0024195855949074, 0.00144941592589021, 0.00173052202444524, 0.00206153257749975, 0.000999248470179737, 0.00117934483569115, 0.00258356356061995, 0.00307703204452991, 0.00163105467800051, 0.000543792732059956, 0.00374460313469172, 0.00178665434941649, 0.00182753382250667, 0.00168480770662427, 0.00185099407099187, 0.00353244505822659, 0.00120945053640753, 0.00170486536808312, 0.00163119600620121, 0.0022314649540931, 0.00329904467798769, 0.00132417061831802, 0.00168515602126718, 0.00237488397397101, 0.00154479418415576, 0.00144463090691715, 0.00182462844531983, 0.00210188794881105, 0.00180717010516673, 0.00176252098754048, 0.00117900467012078 \
  }
#define STAI_NETWORK_WEIGHTS_6_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_7_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_7_NAME "Conv2D_28_weights"
#define STAI_NETWORK_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_7_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_7_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_7_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_7_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_7_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_7_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_7_BATCH (8)
#define STAI_NETWORK_WEIGHTS_7_RANK (5)
#define STAI_NETWORK_WEIGHTS_7_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_7_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_7_SCALES \
  { \
    0.00139899901114404, 0.00143268855754286, 0.00132108351681381, 0.000532849866431206, 0.000883692933712155, 0.00209788396023214, 0.00120972935110331, 0.00137588742654771, 0.00459292344748974, 0.00262858346104622, 0.000982137280516326, 0.00117943168152124, 0.00117660092655569, 0.00206002895720303, 0.00125553912948817, 0.00144454196561128, 0.00104613078292459, 0.00137069774791598, 0.00161435978952795, 0.00152093439828604, 0.000473189778858796, 0.00166851258836687, 0.00197291327640414, 0.00217091641388834, 0.00210568332113326, 0.00214846082963049, 0.00127942336257547, 0.00178538844920695, 0.000877427286468446, 0.00142086413688958, 0.00193504896014929, 0.0026435349136591 \
  }
#define STAI_NETWORK_WEIGHTS_7_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_8_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_8_NAME "Conv2D_32_weights"
#define STAI_NETWORK_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_8_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_8_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_8_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_8_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_8_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_8_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_8_BATCH (8)
#define STAI_NETWORK_WEIGHTS_8_RANK (5)
#define STAI_NETWORK_WEIGHTS_8_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_8_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_8_SCALES \
  { \
    0.00137763645034283, 0.000577518600039184, 0.00144796725362539, 0.0019408380612731, 0.0013134169857949, 0.00329232262447476, 0.00120531325228512, 0.000600360159296542, 0.00145120092201978, 0.00242696073837578, 0.00102197215892375, 0.000522015558090061, 0.00095439376309514, 0.00275603029876947, 0.00124621705617756, 0.000957485055550933, 0.00228931242600083, 0.00109433534089476, 0.00197916571050882, 0.00233631441369653, 0.00218713097274303, 0.00175729999318719, 0.00132130365818739, 0.00121145183220506, 0.00266071478836238, 0.00124368746764958, 0.0015148970996961, 0.000502254697494209, 0.00118054659105837, 0.00265598832629621, 0.00158154335804284, 0.00201585539616644 \
  }
#define STAI_NETWORK_WEIGHTS_8_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_9_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_9_NAME "Conv2D_36_weights"
#define STAI_NETWORK_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_9_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_9_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_9_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_9_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_9_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_9_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_9_BATCH (8)
#define STAI_NETWORK_WEIGHTS_9_RANK (5)
#define STAI_NETWORK_WEIGHTS_9_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_9_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_9_SCALES \
  { \
    0.00124148593749851, 0.00140064070001245, 0.00122740468941629, 0.00255723879672587, 0.00109325221274048, 0.00135568412952125, 0.000878363789524883, 0.000869505864102393, 0.00143010553438216, 0.00112950755283237, 0.0014773701550439, 0.00108799058943987, 0.000532559992279857, 0.00154589605517685, 0.00105232791975141, 0.00116385030560195, 0.000619681843090802, 0.000678583281114697, 0.00159727258142084, 0.00122558092698455, 0.000843681918922812, 0.00133301725145429, 0.00154294236563146, 0.00225981953553855, 0.000764635624364018, 0.000691267661750317, 0.00151638372335583, 0.00112445221748203, 0.000933786213863641, 0.00109392742160708, 0.00114271545317024, 0.00206592679023743 \
  }
#define STAI_NETWORK_WEIGHTS_9_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_10_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_10_NAME "Conv2D_40_weights"
#define STAI_NETWORK_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_10_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_10_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_10_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_10_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_10_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_10_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_10_BATCH (8)
#define STAI_NETWORK_WEIGHTS_10_RANK (5)
#define STAI_NETWORK_WEIGHTS_10_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_10_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_10_SCALES \
  { \
    0.000612998090218753, 0.0022343487944454, 0.00127158546820283, 0.00813279300928116, 0.00160048168618232, 0.00142657128162682, 0.00108452746644616, 0.00205863919109106, 0.00182167859748006, 0.00111464178189635, 0.000906924076844007, 0.00184899137821048, 0.00132902408950031, 0.000953952549025416, 0.00241775228641927, 0.00110344041604549, 0.000842060369905084, 0.00174340046942234, 0.00369062297977507, 0.00273601990193129, 0.000855491263791919, 0.00108939490746707, 0.00195145234465599, 0.00388062931597233, 0.00113554135896266, 0.00186345668043941, 0.00130714650731534, 0.00119790690951049, 0.00225183391012251, 0.00115370645653456, 0.00134460511617362, 0.00136597524397075 \
  }
#define STAI_NETWORK_WEIGHTS_10_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_11_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_11_NAME "Conv2D_44_weights"
#define STAI_NETWORK_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_11_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_11_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_11_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_11_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_11_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_11_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_11_BATCH (8)
#define STAI_NETWORK_WEIGHTS_11_RANK (5)
#define STAI_NETWORK_WEIGHTS_11_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_11_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_11_SCALES \
  { \
    0.00209895288571715, 0.00137904367875308, 0.00145720725413412, 0.0017332237912342, 0.00412221858277917, 0.00342283537611365, 0.00138194102328271, 0.00220177113078535, 0.00175036035943776, 0.00238281348720193, 0.00191790971439332, 0.00126685353461653, 0.00182280573062599, 0.00247658952139318, 0.00127510935999453, 0.00143059424590319, 0.00294445618055761, 0.00180447939783335, 0.00146365561522543, 0.00142576720099896, 0.00421419879421592, 0.00163740885909647, 0.00191675929818302, 0.00179143960122019, 0.00221731537021697, 0.00179276335984468, 0.00128022488206625, 0.00178202660754323, 0.00451074866577983, 0.00190902000758797, 0.00136518804356456, 0.00401701917871833 \
  }
#define STAI_NETWORK_WEIGHTS_11_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_12_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_12_NAME "Conv2D_48_weights"
#define STAI_NETWORK_WEIGHTS_12_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_12_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_12_SIZE (9216)
#define STAI_NETWORK_WEIGHTS_12_SIZE_BYTES (9216)
#define STAI_NETWORK_WEIGHTS_12_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_12_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_12_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_12_BATCH (8)
#define STAI_NETWORK_WEIGHTS_12_RANK (5)
#define STAI_NETWORK_WEIGHTS_12_SHAPE \
  { \
    32, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_12_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_12_SCALES \
  { \
    0.00234469841234386, 0.00235625333152711, 0.00223264680244029, 0.00225609936751425, 0.00192857382353395, 0.00164254859555513, 0.00222142459824681, 0.00274791102856398, 0.00214581424370408, 0.00168968155048788, 0.00226286496035755, 0.00175136490724981, 0.00225726142525673, 0.00136740237940103, 0.00244583515450358, 0.00194522785022855, 0.00293335551396012, 0.00179358688183129, 0.00223375530913472, 0.000861986365634948, 0.00168854219373316, 0.00238443724811077, 0.00246002618223429, 0.00215356168337166, 0.00191888783592731, 0.00180242676287889, 0.00221727113239467, 0.00261878431774676, 0.00262079364620149, 0.00215735728852451, 0.00224869675002992, 0.00163540872745216 \
  }
#define STAI_NETWORK_WEIGHTS_12_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_13_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_13_NAME "Conv2D_51_weights"
#define STAI_NETWORK_WEIGHTS_13_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_13_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_13_SIZE (32)
#define STAI_NETWORK_WEIGHTS_13_SIZE_BYTES (32)
#define STAI_NETWORK_WEIGHTS_13_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_13_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_13_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_13_BATCH (32)
#define STAI_NETWORK_WEIGHTS_13_RANK (4)
#define STAI_NETWORK_WEIGHTS_13_SHAPE \
  { \
    1, 1, 1, 32 \
  }
#define STAI_NETWORK_WEIGHTS_13_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_13_SCALES \
  { \
    0.00303781242109835 \
  }
#define STAI_NETWORK_WEIGHTS_13_OFFSETS \
  { \
    0 \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_WEIGHTS_NUM (0)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_NETWORK_ACTIVATIONS_NUM (0)
#define STAI_NETWORK_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_NETWORK_ORIGIN_MODEL_NAME "model_int8_OE_3_3_1"
#define STAI_NETWORK_C_MODEL_NAME "network"

/*************************** RELATIVE MEMORY POOLS ***************************/
extern unsigned char _mem_pool_xSPI2_network[];

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_NETWORK_H
